//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/ArcadeSystem/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Arcade"",
            ""id"": ""d8858330-efa2-4daa-ba3d-63e5abd3cced"",
            ""actions"": [
                {
                    ""name"": ""P1_Press"",
                    ""type"": ""Button"",
                    ""id"": ""c55be106-491a-4dba-b30b-9ca06286da61"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2_Press"",
                    ""type"": ""Button"",
                    ""id"": ""f94f8acc-59c6-4d24-8a5e-dba0f4dbb67d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P3_Press"",
                    ""type"": ""Button"",
                    ""id"": ""212f98fd-69c6-4f67-b0d5-f99135a8535d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P4_Press"",
                    ""type"": ""Button"",
                    ""id"": ""0c05768f-3124-43c8-a0f6-913ba584a455"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6e9410fc-ab7c-4863-8f0e-bf42dc2437fe"",
                    ""path"": ""<Keyboard>/#(1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1_Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61671bb3-3549-4c1e-90ad-3adbdeb39866"",
                    ""path"": ""<Keyboard>/#(2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2_Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""474370f2-86f1-42fe-b912-d54b69a939f9"",
                    ""path"": ""<Keyboard>/#(3)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P3_Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4de595d7-5f80-4119-8502-7dfa671bbda8"",
                    ""path"": ""<Keyboard>/#(4)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P4_Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Arcade
        m_Arcade = asset.FindActionMap("Arcade", throwIfNotFound: true);
        m_Arcade_P1_Press = m_Arcade.FindAction("P1_Press", throwIfNotFound: true);
        m_Arcade_P2_Press = m_Arcade.FindAction("P2_Press", throwIfNotFound: true);
        m_Arcade_P3_Press = m_Arcade.FindAction("P3_Press", throwIfNotFound: true);
        m_Arcade_P4_Press = m_Arcade.FindAction("P4_Press", throwIfNotFound: true);
    }

    ~@Controls()
    {
        UnityEngine.Debug.Assert(!m_Arcade.enabled, "This will cause a leak and performance issues, Controls.Arcade.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Arcade
    private readonly InputActionMap m_Arcade;
    private List<IArcadeActions> m_ArcadeActionsCallbackInterfaces = new List<IArcadeActions>();
    private readonly InputAction m_Arcade_P1_Press;
    private readonly InputAction m_Arcade_P2_Press;
    private readonly InputAction m_Arcade_P3_Press;
    private readonly InputAction m_Arcade_P4_Press;
    public struct ArcadeActions
    {
        private @Controls m_Wrapper;
        public ArcadeActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @P1_Press => m_Wrapper.m_Arcade_P1_Press;
        public InputAction @P2_Press => m_Wrapper.m_Arcade_P2_Press;
        public InputAction @P3_Press => m_Wrapper.m_Arcade_P3_Press;
        public InputAction @P4_Press => m_Wrapper.m_Arcade_P4_Press;
        public InputActionMap Get() { return m_Wrapper.m_Arcade; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ArcadeActions set) { return set.Get(); }
        public void AddCallbacks(IArcadeActions instance)
        {
            if (instance == null || m_Wrapper.m_ArcadeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ArcadeActionsCallbackInterfaces.Add(instance);
            @P1_Press.started += instance.OnP1_Press;
            @P1_Press.performed += instance.OnP1_Press;
            @P1_Press.canceled += instance.OnP1_Press;
            @P2_Press.started += instance.OnP2_Press;
            @P2_Press.performed += instance.OnP2_Press;
            @P2_Press.canceled += instance.OnP2_Press;
            @P3_Press.started += instance.OnP3_Press;
            @P3_Press.performed += instance.OnP3_Press;
            @P3_Press.canceled += instance.OnP3_Press;
            @P4_Press.started += instance.OnP4_Press;
            @P4_Press.performed += instance.OnP4_Press;
            @P4_Press.canceled += instance.OnP4_Press;
        }

        private void UnregisterCallbacks(IArcadeActions instance)
        {
            @P1_Press.started -= instance.OnP1_Press;
            @P1_Press.performed -= instance.OnP1_Press;
            @P1_Press.canceled -= instance.OnP1_Press;
            @P2_Press.started -= instance.OnP2_Press;
            @P2_Press.performed -= instance.OnP2_Press;
            @P2_Press.canceled -= instance.OnP2_Press;
            @P3_Press.started -= instance.OnP3_Press;
            @P3_Press.performed -= instance.OnP3_Press;
            @P3_Press.canceled -= instance.OnP3_Press;
            @P4_Press.started -= instance.OnP4_Press;
            @P4_Press.performed -= instance.OnP4_Press;
            @P4_Press.canceled -= instance.OnP4_Press;
        }

        public void RemoveCallbacks(IArcadeActions instance)
        {
            if (m_Wrapper.m_ArcadeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IArcadeActions instance)
        {
            foreach (var item in m_Wrapper.m_ArcadeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ArcadeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ArcadeActions @Arcade => new ArcadeActions(this);
    public interface IArcadeActions
    {
        void OnP1_Press(InputAction.CallbackContext context);
        void OnP2_Press(InputAction.CallbackContext context);
        void OnP3_Press(InputAction.CallbackContext context);
        void OnP4_Press(InputAction.CallbackContext context);
    }
}
